import type { Theme, ThemeId } from "./types";

export const THEMES: Record<ThemeId, Theme> = {
  minimal: {
    id: "minimal",
    name: "Minimal",
    bg: "#ffffff",
    surface: "#f7f7f7",
    text: "#0a0a0a",
    muted: "#6b7280",
    accent: "#0a0a0a",
    accentText: "#ffffff",
    fontHead: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    radius: "4px",
  },
  editorial: {
    id: "editorial",
    name: "Editorial",
    bg: "#f5efe6",
    surface: "#ebe3d4",
    text: "#1a1410",
    muted: "#7a6a55",
    accent: "#9a3b1f",
    accentText: "#f5efe6",
    fontHead: "'Playfair Display', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
    radius: "2px",
  },
  corporate: {
    id: "corporate",
    name: "Corporate",
    bg: "#ffffff",
    surface: "#eef2f7",
    text: "#0b1f3a",
    muted: "#52607a",
    accent: "#1e3a8a",
    accentText: "#ffffff",
    fontHead: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    radius: "6px",
  },
  playful: {
    id: "playful",
    name: "Playful",
    bg: "#fff4e6",
    surface: "#ffe0b3",
    text: "#3d1f00",
    muted: "#8b5a2b",
    accent: "#ff6b35",
    accentText: "#ffffff",
    fontHead: "'Poppins', system-ui, sans-serif",
    fontBody: "'Poppins', system-ui, sans-serif",
    radius: "20px",
  },
  darktech: {
    id: "darktech",
    name: "Dark Tech",
    bg: "#0a0e1a",
    surface: "#141a2b",
    text: "#e8ecf5",
    muted: "#7a8499",
    accent: "#3ee6c4",
    accentText: "#0a0e1a",
    fontHead: "'JetBrains Mono', 'Inter', monospace",
    fontBody: "'Inter', system-ui, sans-serif",
    radius: "2px",
  },
  warm: {
    id: "warm",
    name: "Warm",
    bg: "#f4ebe0",
    surface: "#e8d8c4",
    text: "#3a2418",
    muted: "#7a5a45",
    accent: "#b85042",
    accentText: "#f4ebe0",
    fontHead: "'Lora', Georgia, serif",
    fontBody: "'Inter', system-ui, sans-serif",
    radius: "8px",
  },
};

export const THEME_LIST = Object.values(THEMES);
